version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'User'
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: 'sls_db'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
